# Generated by Django 4.0.1 on 2022-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_remove_user_email_remove_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, null=True)),
                ('iban', models.CharField(max_length=24, null=True)),
                ('account_type', models.CharField(max_length=15, null=True)),
                ('currency', models.CharField(max_length=5, null=True)),
                ('sold', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banking_account_id', models.CharField(max_length=10, null=True)),
                ('card_number', models.CharField(max_length=16, null=True)),
                ('expiration_date', models.CharField(max_length=5, null=True)),
                ('cvv', models.CharField(max_length=3, null=True)),
                ('card_type', models.BooleanField(default=0)),
                ('card_status', models.BooleanField(default=0)),
                ('pin', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banking_account_id', models.CharField(max_length=10, null=True)),
                ('transaction_type', models.CharField(max_length=20, null=True)),
                ('amount', models.FloatField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('card_id', models.CharField(max_length=10, null=True)),
                ('receiver_iban', models.CharField(max_length=24, null=True)),
                ('receiver_name', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('id_series', models.CharField(max_length=2, null=True)),
                ('id_number', models.CharField(max_length=6, null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNP', models.CharField(max_length=13, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
