# Generated by Django 4.0.1 on 2022-02-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bankingaccounts_cards_transactions_userdata_users_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
