# Generated by Django 4.0.1 on 2022-02-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_users_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankingAccounts',
            new_name='BankingAccount',
        ),
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='bankingaccount',
            table='banking_accounts',
        ),
        migrations.AlterModelTable(
            name='card',
            table='cards',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='userdata',
            table='users_data',
        ),
    ]
