# Generated by Django 4.0.1 on 2022-02-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_bankingaccounts_bankingaccount_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='USErs',
        ),
    ]
