# Generated by Django 4.0.1 on 2022-02-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdata',
            table='USErs_data',
        ),
    ]
