# Generated by Django 4.0.1 on 2022-02-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='userdata',
            table='users_data',
        ),
    ]
