# Generated by Django 4.0.1 on 2022-02-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_table_alter_userdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=10, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('id_series', models.CharField(max_length=2, null=True)),
                ('id_number', models.CharField(max_length=6, null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'customers_data',
            },
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.RenameField(
            model_name='bankingaccount',
            old_name='user_id',
            new_name='customer_id',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
    ]
