# Generated by Django 4.0.1 on 2022-02-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankingaccount',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='banking_account_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='banking_account_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='bankingaccount',
            table=None,
        ),
        migrations.AlterModelTable(
            name='card',
            table=None,
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='customerdata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='transaction',
            table=None,
        ),
    ]
