# Generated by Django 4.0.1 on 2022-02-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_bankingaccount_customer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='customerdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customerdata',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customerdata',
            name='CNP',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
