# Generated by Django 4.0.1 on 2022-02-13 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_customerdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankingaccount',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='banking_account_id',
        ),
        migrations.RemoveField(
            model_name='customerdata',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='banking_account_id',
        ),
        migrations.AddField(
            model_name='bankingaccount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='banking_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankingaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='banking_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankingaccount'),
        ),
    ]
