# Generated by Django 4.0.1 on 2022-02-13 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_bankingaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='banking_account',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.bankingaccount'),
        ),
    ]
